package edu.tyut.bean.mgb;

import java.io.Serializable;

public class AcademicCredit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academic_credit.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academic_credit.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academic_credit.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column academic_credit.credit
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer credit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academic_credit.id
     *
     * @return the value of academic_credit.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academic_credit.id
     *
     * @param id the value for academic_credit.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academic_credit.student_id
     *
     * @return the value of academic_credit.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academic_credit.student_id
     *
     * @param studentId the value for academic_credit.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academic_credit.student_name
     *
     * @return the value of academic_credit.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academic_credit.student_name
     *
     * @param studentName the value for academic_credit.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column academic_credit.credit
     *
     * @return the value of academic_credit.credit
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column academic_credit.credit
     *
     * @param credit the value for academic_credit.credit
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
}