package edu.tyut.bean.mgb;

import java.io.Serializable;
import java.util.Date;

public class County implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.COUNTY_ID
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.COUNTY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String countyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.CITY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.COUNTY_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String countyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.SHORT_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.LNG
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.LAT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.SORT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.GMT_CREATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.GMT_MODIFIED
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.MEMO
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.DATA_STATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private Integer dataState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.TENANT_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    private String tenantCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.COUNTY_ID
     *
     * @return the value of county.COUNTY_ID
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.COUNTY_ID
     *
     * @param countyId the value for county.COUNTY_ID
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.COUNTY_CODE
     *
     * @return the value of county.COUNTY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.COUNTY_CODE
     *
     * @param countyCode the value for county.COUNTY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode == null ? null : countyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.CITY_CODE
     *
     * @return the value of county.CITY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.CITY_CODE
     *
     * @param cityCode the value for county.CITY_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.COUNTY_NAME
     *
     * @return the value of county.COUNTY_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.COUNTY_NAME
     *
     * @param countyName the value for county.COUNTY_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.SHORT_NAME
     *
     * @return the value of county.SHORT_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.SHORT_NAME
     *
     * @param shortName the value for county.SHORT_NAME
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.LNG
     *
     * @return the value of county.LNG
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.LNG
     *
     * @param lng the value for county.LNG
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.LAT
     *
     * @return the value of county.LAT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.LAT
     *
     * @param lat the value for county.LAT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.SORT
     *
     * @return the value of county.SORT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.SORT
     *
     * @param sort the value for county.SORT
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.GMT_CREATE
     *
     * @return the value of county.GMT_CREATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.GMT_CREATE
     *
     * @param gmtCreate the value for county.GMT_CREATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.GMT_MODIFIED
     *
     * @return the value of county.GMT_MODIFIED
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.GMT_MODIFIED
     *
     * @param gmtModified the value for county.GMT_MODIFIED
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.MEMO
     *
     * @return the value of county.MEMO
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.MEMO
     *
     * @param memo the value for county.MEMO
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.DATA_STATE
     *
     * @return the value of county.DATA_STATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public Integer getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.DATA_STATE
     *
     * @param dataState the value for county.DATA_STATE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setDataState(Integer dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.TENANT_CODE
     *
     * @return the value of county.TENANT_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.TENANT_CODE
     *
     * @param tenantCode the value for county.TENANT_CODE
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode == null ? null : tenantCode.trim();
    }
}