package edu.tyut.bean.mgb;

import java.io.Serializable;

public class ElectiveScore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.elective_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer electiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.elective_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String electiveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elective_score.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.id
     *
     * @return the value of elective_score.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.id
     *
     * @param id the value for elective_score.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.student_id
     *
     * @return the value of elective_score.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.student_id
     *
     * @param studentId the value for elective_score.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.student_name
     *
     * @return the value of elective_score.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.student_name
     *
     * @param studentName the value for elective_score.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.elective_id
     *
     * @return the value of elective_score.elective_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getElectiveId() {
        return electiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.elective_id
     *
     * @param electiveId the value for elective_score.elective_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setElectiveId(Integer electiveId) {
        this.electiveId = electiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.elective_name
     *
     * @return the value of elective_score.elective_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getElectiveName() {
        return electiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.elective_name
     *
     * @param electiveName the value for elective_score.elective_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setElectiveName(String electiveName) {
        this.electiveName = electiveName == null ? null : electiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elective_score.score
     *
     * @return the value of elective_score.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elective_score.score
     *
     * @param score the value for elective_score.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}