package edu.tyut.bean.mgb;

import java.io.Serializable;

public class PoliticalStatus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column political_status.id
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column political_status.status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column political_status.id
     *
     * @return the value of political_status.id
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column political_status.id
     *
     * @param id the value for political_status.id
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column political_status.status
     *
     * @return the value of political_status.status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column political_status.status
     *
     * @param status the value for political_status.status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}