package edu.tyut.bean.mgb;

import java.io.Serializable;

public class PoliticalStatus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column political_status.status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column political_status.status
     *
     * @return the value of political_status.status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column political_status.status
     *
     * @param status the value for political_status.status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}