package edu.tyut.bean.mgb;

public class Profession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.name
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.count
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String academy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.introduction
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.name
     *
     * @return the value of profession.name
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.name
     *
     * @param name the value for profession.name
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.count
     *
     * @return the value of profession.count
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.count
     *
     * @param count the value for profession.count
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.academy
     *
     * @return the value of profession.academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.academy
     *
     * @param academy the value for profession.academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.introduction
     *
     * @return the value of profession.introduction
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.introduction
     *
     * @param introduction the value for profession.introduction
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}