package edu.tyut.bean.mgb;

import java.io.Serializable;
import java.util.Date;

public class Province implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.PROVINCE_ID
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.PROVINCE_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.PROVINCE_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.SHORT_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.LNG
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.LAT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.SORT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.GMT_CREATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.GMT_MODIFIED
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.MEMO
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.DATA_STATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private Integer dataState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.TENANT_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    private String tenantCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.PROVINCE_ID
     *
     * @return the value of province.PROVINCE_ID
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.PROVINCE_ID
     *
     * @param provinceId the value for province.PROVINCE_ID
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.PROVINCE_CODE
     *
     * @return the value of province.PROVINCE_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.PROVINCE_CODE
     *
     * @param provinceCode the value for province.PROVINCE_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.PROVINCE_NAME
     *
     * @return the value of province.PROVINCE_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.PROVINCE_NAME
     *
     * @param provinceName the value for province.PROVINCE_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.SHORT_NAME
     *
     * @return the value of province.SHORT_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.SHORT_NAME
     *
     * @param shortName the value for province.SHORT_NAME
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.LNG
     *
     * @return the value of province.LNG
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.LNG
     *
     * @param lng the value for province.LNG
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.LAT
     *
     * @return the value of province.LAT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.LAT
     *
     * @param lat the value for province.LAT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.SORT
     *
     * @return the value of province.SORT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.SORT
     *
     * @param sort the value for province.SORT
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.GMT_CREATE
     *
     * @return the value of province.GMT_CREATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.GMT_CREATE
     *
     * @param gmtCreate the value for province.GMT_CREATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.GMT_MODIFIED
     *
     * @return the value of province.GMT_MODIFIED
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.GMT_MODIFIED
     *
     * @param gmtModified the value for province.GMT_MODIFIED
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.MEMO
     *
     * @return the value of province.MEMO
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.MEMO
     *
     * @param memo the value for province.MEMO
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.DATA_STATE
     *
     * @return the value of province.DATA_STATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public Integer getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.DATA_STATE
     *
     * @param dataState the value for province.DATA_STATE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setDataState(Integer dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.TENANT_CODE
     *
     * @return the value of province.TENANT_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.TENANT_CODE
     *
     * @param tenantCode the value for province.TENANT_CODE
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode == null ? null : tenantCode.trim();
    }
}