package edu.tyut.bean.mgb;

import java.io.Serializable;

public class RewardAndPunishment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_and_punishment.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_and_punishment.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_and_punishment.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_and_punishment.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_and_punishment.reason
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_and_punishment.id
     *
     * @return the value of reward_and_punishment.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_and_punishment.id
     *
     * @param id the value for reward_and_punishment.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_and_punishment.student_id
     *
     * @return the value of reward_and_punishment.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_and_punishment.student_id
     *
     * @param studentId the value for reward_and_punishment.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_and_punishment.student_name
     *
     * @return the value of reward_and_punishment.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_and_punishment.student_name
     *
     * @param studentName the value for reward_and_punishment.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_and_punishment.score
     *
     * @return the value of reward_and_punishment.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_and_punishment.score
     *
     * @param score the value for reward_and_punishment.score
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_and_punishment.reason
     *
     * @return the value of reward_and_punishment.reason
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_and_punishment.reason
     *
     * @param reason the value for reward_and_punishment.reason
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}