package edu.tyut.bean.mgb;

import java.io.Serializable;

public class TransferInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.pre_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String preAcademy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.pre_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String preProfession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.pre_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String preCls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.post_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String postAcademy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.post_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String postProfession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_info.post_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    private String postCls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.id
     *
     * @return the value of transfer_info.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.id
     *
     * @param id the value for transfer_info.id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.student_id
     *
     * @return the value of transfer_info.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.student_id
     *
     * @param studentId the value for transfer_info.student_id
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.student_name
     *
     * @return the value of transfer_info.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.student_name
     *
     * @param studentName the value for transfer_info.student_name
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.pre_academy
     *
     * @return the value of transfer_info.pre_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPreAcademy() {
        return preAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.pre_academy
     *
     * @param preAcademy the value for transfer_info.pre_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPreAcademy(String preAcademy) {
        this.preAcademy = preAcademy == null ? null : preAcademy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.pre_profession
     *
     * @return the value of transfer_info.pre_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPreProfession() {
        return preProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.pre_profession
     *
     * @param preProfession the value for transfer_info.pre_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPreProfession(String preProfession) {
        this.preProfession = preProfession == null ? null : preProfession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.pre_cls
     *
     * @return the value of transfer_info.pre_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPreCls() {
        return preCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.pre_cls
     *
     * @param preCls the value for transfer_info.pre_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPreCls(String preCls) {
        this.preCls = preCls == null ? null : preCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.post_academy
     *
     * @return the value of transfer_info.post_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPostAcademy() {
        return postAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.post_academy
     *
     * @param postAcademy the value for transfer_info.post_academy
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPostAcademy(String postAcademy) {
        this.postAcademy = postAcademy == null ? null : postAcademy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.post_profession
     *
     * @return the value of transfer_info.post_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPostProfession() {
        return postProfession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.post_profession
     *
     * @param postProfession the value for transfer_info.post_profession
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPostProfession(String postProfession) {
        this.postProfession = postProfession == null ? null : postProfession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_info.post_cls
     *
     * @return the value of transfer_info.post_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public String getPostCls() {
        return postCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_info.post_cls
     *
     * @param postCls the value for transfer_info.post_cls
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public void setPostCls(String postCls) {
        this.postCls = postCls == null ? null : postCls.trim();
    }
}