package edu.tyut.service;

import edu.tyut.bean.mgb.City;
import edu.tyut.bean.mgb.CityExample;
import edu.tyut.dao.CityMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class CityService {

    private final CityMapper cityMapper;

    public CityService(CityMapper cityMapper) {
        this.cityMapper = cityMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public long countByExample(CityExample example) {
        return cityMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int deleteByExample(CityExample example) {
        return cityMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int insert(City record) {
        return cityMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int insertSelective(City record) {
        return cityMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public List<City> selectByExample(CityExample example) {
        return cityMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int updateByExampleSelective(@Param("record") City record,
                                 @Param("example") CityExample example)
    {
        return cityMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int updateByExample(@Param("record") City record,
                        @Param("example") CityExample example)
    {
        return cityMapper.updateByExample(record, example);
    }

    public City selectByCityCode(Integer code) {
        return cityMapper.selectByCityCode(code);
    }

    public List<City> selectAll() {
        return cityMapper.selectAll();
    }
}
