package edu.tyut.service;

import edu.tyut.bean.mgb.County;
import edu.tyut.bean.mgb.CountyExample;
import edu.tyut.dao.CountyMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class CountyService {

    private CountyMapper countyMapper;

    public CountyService(CountyMapper countyMapper) {
        this.countyMapper = countyMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public long countByExample(CountyExample example) {
        return countyMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public int deleteByExample(CountyExample example) {
        return countyMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public int insert(County record) {
        return countyMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public int insertSelective(County record) {
        return countyMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public List<County> selectByExample(CountyExample example) {
        return countyMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public int updateByExampleSelective(@Param("record") County record,
                                 @Param("example") CountyExample example)
    {
        return countyMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Mon Jun 01 17:31:13 CST 2020
     */
    public int updateByExample(@Param("record") County record,
                        @Param("example") CountyExample example)
    {
        return countyMapper.updateByExample(record, example);
    }

}
