package edu.tyut.service;

import edu.tyut.bean.mgb.Ethnic;
import edu.tyut.bean.mgb.EthnicExample;
import edu.tyut.dao.EthnicMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class EthnicService {

    private EthnicMapper ethnicMapper;

    public EthnicService(EthnicMapper ethnicMapper) {
        this.ethnicMapper = ethnicMapper;
    }

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public long countByExample(EthnicExample example) {
        return ethnicMapper.countByExample(example);
    }*/

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public int deleteByExample(EthnicExample example) {
        return ethnicMapper.deleteByExample(example);
    }*/

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public int insert(Ethnic record) {
        return ethnicMapper.insert(record);
    }*/

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public int insertSelective(Ethnic record) {
        return ethnicMapper.insertSelective(record);
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    public List<Ethnic> selectByExample(EthnicExample example) {
        return ethnicMapper.selectByExample(example);
    }

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public int updateByExampleSelective(@Param("record") Ethnic record,
                                 @Param("example") EthnicExample example)
    {
        return ethnicMapper.updateByExampleSelective(record, example);
    }*/

    /*
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun May 31 17:14:33 CST 2020
     */
    /*public int updateByExample(@Param("record") Ethnic record,
                        @Param("example") EthnicExample example)
    {
        return ethnicMapper.updateByExample(record, example);
    }*/

}
