package edu.tyut.service;

import edu.tyut.bean.mgb.Manager;
import edu.tyut.bean.mgb.ManagerExample;
import edu.tyut.dao.ManagerMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ManagerService {
    
    private ManagerMapper managerMapper;
    
    public ManagerService(ManagerMapper managerMapper) {
        this.managerMapper = managerMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public long countByExample(ManagerExample example) {
        return managerMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int deleteByExample(ManagerExample example) {
        return managerMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int insert(Manager record) {
        return managerMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int insertSelective(Manager record) {
        return managerMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public List<Manager> selectByExample(ManagerExample example) {
        return managerMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int updateByExampleSelective(@Param("record") Manager record,
                                 @Param("example") ManagerExample example)
    {
        return managerMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int updateByExample(@Param("record") Manager record,
                        @Param("example") ManagerExample example)
    {
        return managerMapper.updateByExample(record, example);
    }

}
