package edu.tyut.service;

import edu.tyut.bean.mgb.PoliticalStatus;
import edu.tyut.bean.mgb.PoliticalStatusExample;
import edu.tyut.dao.PoliticalStatusMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PoliticalStatusService {

    private PoliticalStatusMapper politicalStatusMapper;

    public PoliticalStatusService(PoliticalStatusMapper politicalStatusMapper) {
        this.politicalStatusMapper = politicalStatusMapper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public long countByExample(PoliticalStatusExample example) {
        return politicalStatusMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public int deleteByExample(PoliticalStatusExample example) {
        return politicalStatusMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public int insert(PoliticalStatus record) {
        return politicalStatusMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public int insertSelective(PoliticalStatus record) {
        return politicalStatusMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public List<PoliticalStatus> selectByExample(PoliticalStatusExample example) {
        return politicalStatusMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public int updateByExampleSelective(@Param("record") PoliticalStatus record,
                                 @Param("example") PoliticalStatusExample example)
    {
        return politicalStatusMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Mon Jun 01 18:34:25 CST 2020
     */
    public int updateByExample(@Param("record") PoliticalStatus record,
                        @Param("example") PoliticalStatusExample example)
    {
        return politicalStatusMapper.updateByExample(record, example);
    }

}
