package edu.tyut.service;

import edu.tyut.bean.mgb.Province;
import edu.tyut.bean.mgb.ProvinceExample;
import edu.tyut.dao.ProvinceMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ProvinceService {

    private final ProvinceMapper provinceMapper;

    public ProvinceService(ProvinceMapper provinceMapper) {
        this.provinceMapper = provinceMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public long countByExample(ProvinceExample example) {
        return provinceMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int deleteByExample(ProvinceExample example) {
        return provinceMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int insert(Province record) {
        return provinceMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int insertSelective(Province record) {
        return provinceMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public List<Province> selectByExample(ProvinceExample example) {
        return provinceMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    public int updateByExampleSelective(@Param("record") Province record,
                                 @Param("example") ProvinceExample example)
    {
        return provinceMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 13:31:51 CST 2020
     */
    int updateByExample(@Param("record") Province record,
                        @Param("example") ProvinceExample example)
    {
        return provinceMapper.updateByExample(record, example);
    }

    public Province selectByProvinceCode(Integer code) {
        return provinceMapper.selectByProvinceCode(code);
    }

    public List<Province> selectAll() {
        return provinceMapper.selectAll();
    }
}
