package edu.tyut.service;

import edu.tyut.bean.mgb.Student;
import edu.tyut.bean.mgb.StudentExample;
import edu.tyut.dao.StudentMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class StudentService {

    private StudentMapper studentMapper;

    public StudentService(StudentMapper studentMapper) {
        this.studentMapper = studentMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public long countByExample(StudentExample example) {
        return studentMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public int deleteByExample(StudentExample example) {
        return studentMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public int insert(Student record) {
        return studentMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public int insertSelective(Student record) {
        return studentMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public List<Student> selectByExample(StudentExample example) {
        return studentMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public int updateByExampleSelective(@Param("record") Student record,
                                 @Param("example") StudentExample example)
    {
        return studentMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jun 01 16:25:49 CST 2020
     */
    public int updateByExample(@Param("record") Student record,
                        @Param("example") StudentExample example)
    {
        return studentMapper.updateByExample(record, example);
    }

}
