package edu.tyut.service;

import edu.tyut.bean.mgb.Teacher;
import edu.tyut.bean.mgb.TeacherExample;
import edu.tyut.dao.TeacherMapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TeacherService {

    private TeacherMapper teacherMapper;

    public TeacherService(TeacherMapper teacherMapper) {
        this.teacherMapper = teacherMapper;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public long countByExample(TeacherExample example) {
        return teacherMapper.countByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int deleteByExample(TeacherExample example) {
        return teacherMapper.deleteByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int insert(Teacher record) {
        return teacherMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int insertSelective(Teacher record) {
        return teacherMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public List<Teacher> selectByExample(TeacherExample example) {
        return teacherMapper.selectByExample(example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int updateByExampleSelective(@Param("record") Teacher record,
                                 @Param("example") TeacherExample example)
    {
        return teacherMapper.updateByExampleSelective(record, example);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    public int updateByExample(@Param("record") Teacher record,
                        @Param("example") TeacherExample example)
    {
        return teacherMapper.updateByExample(record, example);
    }

}
