package edu.tyut.dao;

import edu.tyut.bean.mbg.AcademicCredit;
import edu.tyut.bean.mbg.AcademicCreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcademicCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(AcademicCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(AcademicCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(AcademicCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(AcademicCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<AcademicCredit> selectByExample(AcademicCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") AcademicCredit record, @Param("example") AcademicCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academic_credit
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") AcademicCredit record, @Param("example") AcademicCreditExample example);
}