package edu.tyut.dao;

import edu.tyut.bean.mgb.Academy;
import edu.tyut.bean.mgb.AcademyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<Academy> selectByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") Academy record, @Param("example") AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") Academy record, @Param("example") AcademyExample example);
}