package edu.tyut.dao;

import edu.tyut.bean.mgb.City;
import edu.tyut.bean.mgb.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    long countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Sun May 31 14:21:32 CST 2020
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    City selectByCityCode(Integer code);

    List<City> selectAll();
}