package edu.tyut.dao;

import edu.tyut.bean.mgb.Electives;
import edu.tyut.bean.mgb.ElectivesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElectivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    long countByExample(ElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int deleteByExample(ElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insert(Electives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insertSelective(Electives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    List<Electives> selectByExample(ElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") Electives record, @Param("example") ElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electives
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExample(@Param("record") Electives record, @Param("example") ElectivesExample example);
}