package edu.tyut.dao;

import edu.tyut.bean.mbg.Ethnic;
import edu.tyut.bean.example.EthnicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EthnicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(EthnicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(EthnicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(Ethnic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(Ethnic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<Ethnic> selectByExample(EthnicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") Ethnic record, @Param("example") EthnicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") Ethnic record, @Param("example") EthnicExample example);
}