package edu.tyut.dao;

import edu.tyut.bean.mgb.ManagerLogin;
import edu.tyut.bean.mgb.ManagerLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    long countByExample(ManagerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int deleteByExample(ManagerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insert(ManagerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insertSelective(ManagerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    List<ManagerLogin> selectByExample(ManagerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") ManagerLogin record, @Param("example") ManagerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExample(@Param("record") ManagerLogin record, @Param("example") ManagerLoginExample example);
}