package edu.tyut.dao;

import edu.tyut.bean.mgb.PoliticalStatus;
import edu.tyut.bean.mgb.PoliticalStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoliticalStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(PoliticalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(PoliticalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<PoliticalStatus> selectByExample(PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") PoliticalStatus record, @Param("example") PoliticalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table political_status
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") PoliticalStatus record, @Param("example") PoliticalStatusExample example);
}