package edu.tyut.dao;

import edu.tyut.bean.mbg.Profession;
import edu.tyut.bean.example.ProfessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<Profession> selectByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") Profession record, @Param("example") ProfessionExample example);
}