package edu.tyut.dao;

import edu.tyut.bean.mgb.Province;
import edu.tyut.bean.mgb.ProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    long countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbg.generated Sun May 31 14:21:31 CST 2020
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    Province selectByProvinceCode(Integer code);

    List<Province> selectAll();
}