package edu.tyut.dao;

import edu.tyut.bean.mbg.StudentElectives;
import edu.tyut.bean.mbg.StudentElectivesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentElectivesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    long countByExample(StudentElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int deleteByExample(StudentElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insert(StudentElectives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int insertSelective(StudentElectives record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    List<StudentElectives> selectByExample(StudentElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentElectives record, @Param("example") StudentElectivesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_electives
     *
     * @mbg.generated Fri Jun 05 21:19:30 CST 2020
     */
    int updateByExample(@Param("record") StudentElectives record, @Param("example") StudentElectivesExample example);
}