package edu.tyut.dao;

import edu.tyut.bean.mgb.TeacherLogin;
import edu.tyut.bean.mgb.TeacherLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    long countByExample(TeacherLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int deleteByExample(TeacherLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insert(TeacherLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insertSelective(TeacherLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    List<TeacherLogin> selectByExample(TeacherLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TeacherLogin record, @Param("example") TeacherLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_login
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExample(@Param("record") TeacherLogin record, @Param("example") TeacherLoginExample example);
}