package edu.tyut.dao;

import edu.tyut.bean.mgb.TransferInfo;
import edu.tyut.bean.mgb.TransferInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    long countByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int deleteByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insert(TransferInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int insertSelective(TransferInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    List<TransferInfo> selectByExample(TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TransferInfo record, @Param("example") TransferInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_info
     *
     * @mbg.generated Mon Jun 01 14:23:16 CST 2020
     */
    int updateByExample(@Param("record") TransferInfo record, @Param("example") TransferInfoExample example);
}